apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::659230814117:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-ZIEF66NKELEE
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::659230814117:role/UdacityFlaskDeployCBKubectlRole
      username: build
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2021-02-13T12:51:25Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:mapRoles: {}
        f:mapUsers: {}
    manager: eksctl.exe
    operation: Update
    time: "2021-02-13T12:51:25Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "2134"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: 074db649-ba4d-4aea-b308-de55faa93fde
